version: '3.8'

services:
  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - safesphere_network

  # Frontend (removed - hosting on Vercel)
  # The frontend will be hosted separately on Vercel

  # Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - backend_static:/app/staticfiles
      - backend_media:/app/media
      - backend_logs:/app/logs
    env_file:
      - .env.prod
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - safesphere_network

  # Celery worker
  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: ["/opt/venv/bin/celery", "-A", "core", "worker", "--loglevel=info"]
    volumes:
      - backend_media:/app/media
      - backend_logs:/app/logs
    env_file:
      - .env.prod
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - safesphere_network

  # Celery beat (scheduler)
  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: ["/opt/venv/bin/celery", "-A", "core", "beat", "--loglevel=info"]
    volumes:
      - backend_logs:/app/logs
    env_file:
      - .env.prod
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - safesphere_network

  # Database (External Render PostgreSQL - no local database needed)
  # The backend will connect directly to Render PostgreSQL

  # Redis
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - safesphere_network

  # Backup service (removed - using external Render PostgreSQL)
  # Manual backups can be done using: ./deploy.sh backup

volumes:
  redis_data:
  backend_static:
  backend_media:
  backend_logs:
  nginx_logs:

networks:
  safesphere_network:
    driver: bridge 